repo_id: "vla_data_lerobot"
dataset_path: "/home/hongyi/DATA/bootcamp_data/vla_data_lerobot"
checkpoint_path: /hkfs/work/workspace/scratch/uhtfz-flower/360000_model_weight.pt

train:
  batch_size: 2
  steps: 40000
  save_freq: 100
  seed: 42
  device: cuda
  num_workers: 1
  log_freq: 100
  output_dir: "./output/beast/"
  job_name: "model_training"
  push_to_hub: false
  #Only pi0/pi05
  gradient_checkpointing: true
  compile_model: false

wandb:
  enable: true
  project: "lerobot-beast-training"
  entity: "zhouhongyi"
  mode: "online"
