seed: 42
device: cuda
checkpoint_path: null # Path to your checkpoint file or directory
stats_path: /path/to/your/dataset/stats.json # for evaluation for flower
wandb:
  project: "lerobot-pi0-eval"
  entity: "your_wandb_entity"
  mode: "disabled"
